import { createSlice } from '@reduxjs/toolkit'; // Import createSlice from Redux Toolkit

// Create a slice of the Redux store for managing form data
const formSlice = createSlice({
  name: 'form', // Name of the slice
  initialState: {
    name: '', // Initial state for the name input
    cost: 0, // Initial state for the cost input
  },
  reducers: {
    // Action to change the name in the form
    changeName: (state, action) => {
      state.name = action.payload; // Update the name in the state
    },

    // Action to change the cost in the form
    changeCost: (state, action) => {
      state.cost = action.payload; // Update the cost in the state
    },
  },
});

// Export the actions generated by createSlice
export const { changeName, changeCost } = formSlice.actions;
// Export the reducer to be used in the store
export const formReducer = formSlice.reducer;
